version: '3.9'
networks:
    demo_sqli:
volumes:
    db_data:
services:
    web:
        build: ./app
        container_name: web_demo
        depends_on:
            - db
        ports:
            - "8080:8080"
        networks:
            - demo_sqli
    db:
        image: mysql:8
        container_name: mysql
        restart: always
        ports:
             - "3307:3306"
        environment:
            MYSQL_USER: demo
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
            MYSQL_DATABASE: demo_sqli
        volumes:
            - db_data:/var/lib/mysql
            - ./db:/docker-entrypoint-initdb.d
        networks:
            - demo_sqli

          
            
